version: "3.6"
services:
  springapp:
    image: sachindockeregister/springappwithencryptedcred:1
    ports: 
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=mymongoapp
    - MONGO_DB_USERNAME=sachin
    - MONGO_DB_PASSWORD=secret123
    networks:
    - springbootNetwork
    depends_on:
    - mymongoapp

  mymongoapp:
    image: mongo:4.4
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=sachin
    - MONGO_INITDB_ROOT_PASSWORD=secret123
    networks:
    - springbootNetwork
    volumes:
    - mongovol:/data/db
    

volumes:
  mongovol:
    driver: local # external: true

networks:
  springbootNetwork:
    driver: bridge # external: true
