spring:
  data:
    mongodb:
      uri: mongodb://sachin:secret123@mymongoapp:27017/users?authSource=admin
      management:
        endpoints:
          web:
            exposure:
              include: health,info
      endpoint:
        health:
          show-details: always
        
server:
  port: 8080
