spring:
  data:
    mongodb:
      #uri: mongodb://sachin:secret123@mymongoapp:27017/users?authSource=admin
      uri: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOSTNAME}:27017/users?authSource=admin
      management:
        endpoints:
          web:
            exposure:
              include: health,info
      endpoint:
        health:
          show-details: always
        
server:
  port: 8080
